config/routes.rb
Rails.application.routes.draw do
  namespace :cmsino do 
    resources :contents do
      resources :media do 
        put :toggle, on: :member
      end
      resources :media_uses
    end
    resources :media

    resources :pages
    resources :posts
    resources :media_uses
  end
end

app/models/cmsino/content.rb
# umbrella can be the name of the page
# or the group of Cmsino::Post 
# (posts are CmsinoContent with type="Cmsino::Post")
class Cmsino::Content < ActiveRecord::Base
  self.table_name = 'cmsino_contents'

  has_many :cmsino_media_uses, class_name: "Cmsino::MediaUse", foreign_key: "cmsino_content_id", dependent: :destroy
  has_many :cmsino_media, through: :cmsino_media_uses, class_name: "Cmsino::Medium"

  validates_presence_of   :name, :locale
  validates_uniqueness_of :name, scope: [:umbrella, :locale]

  def to_s
    self.title ? self.title : self.name
  end

  def div_id
    self.umbrella + self.name + self.locale
  end
end

app/models/cmsino/event_content.rb
class Cmsino::EventContent < Cmsino::Content


end

app/models/cmsino/media_use.rb
class Cmsino::MediaUse < ActiveRecord::Base
  self.table_name = 'cmsino_media_uses'

  belongs_to :cmsino_content, class_name: "Cmsino::Content", foreign_key: "cmsino_content_id"
  belongs_to :cmsino_medium,  class_name: "Cmsino::Medium",  foreign_key: "cmsino_medium_id"
end

app/models/cmsino/medium.rb
class Cmsino::Medium < ActiveRecord::Base
  self.table_name = 'cmsino_media'

  has_many :cmsino_media_uses, class_name: "Cmsino::MediaUse", foreign_key: "cmsino_medium_id", dependent: :destroy
  has_many :cmsino_contents, through: :cmsino_media_uses, class_name: "Cmsino::Content"

  has_attached_file :attach,
                    styles: { medium: "300x300>", thumb: "100x100>" } 
  validates_attachment_content_type :attach, content_type: /\Aimage\/.*\Z/

  validates_presence_of   :name 
  validates_uniqueness_of :name

  def to_s
    self.name
  end
end

app/models/cmsino/page.rb
# In database the contents in the same page have the same umbrella.
class Cmsino::Page
  attr_reader :name, :description

  def initialize(name, description = nil)
    @name = name
    @cmsino_conf = Cmsino::Conf.instance
    @description = description || name
  end

  def content(content_name, locale)
    Cmsino::Content.find_or_create_by(umbrella: self.name, name: content_name, locale: validate_locale(locale))
  end

  def medium(content_name)
    Cmsino::Medium.find_or_create_by(umbrella: self.name, name: content_name)
  end

  def validate_locale(locale)
    @cmsino_conf.locales.include?(locale.to_s) ? locale.to_s : 'en'
  end

  # contents belongs to sabe page if have page name as umbrella
  def contents
    Cmsino::Content.where(umbrella: self.name).order(:locale)
  end

  # return has with locales as key anc contents as value
  def contents_locales_hash
    Cmsino::Content.where(umbrella: self.name).inject({}){|res,c| res[c.locale] = c; res}
  end

end

app/models/cmsino/post.rb
class Cmsino::Post < Cmsino::Content
  validates_presence_of :umbrella
  validates_presence_of :name

  before_save :set_date

  def set_date
    self.date = Time.now
  end
end

app/controllers/cmsino/contents_controller.rb
class Cmsino::ContentsController < ApplicationController
  layout false
  authorize_resource class: Cmsino::Content

  def new 
    if params[:cmsino_post]
      @content = Cmsino::Post.new(cmsino_content_params)
    else
      @content = Cmsino::Content.new(cmsino_content_params)
    end

    @all_content_locales = Cmsino::Content.where(umbrella: @content.umbrella, 
                                                 name:     @content.name)
    render action: :edit
  end

  # "cmsino_content"=>{"umbrella"=>"page_name", "name"=>"content_name", "locale"=>"en", "text"=>"<p>my text</p>"}
  def create
    if params[:cmsino_post]
      @content = Cmsino::Post.new(cmsino_content_params)
    else
      @content = Cmsino::Content.new(cmsino_content_params)
    end
    session[:cmsino_last] = @content.div_id
    if @content.save
      redirect_to action: :index, notice: 'OK'
    else
      render action: :edit
    end
  end

  def edit
    session[:cmsino_from] = request.env["HTTP_REFERER"]
    @content = Cmsino::Content.find(params[:id])
    @all_content_locales = Cmsino::Content.where(umbrella: @content.umbrella, name: @content.name)
  end

  def update
    @content = Cmsino::Content.find(params[:id])
    session[:cmsino_last] = @content.div_id
    @content.update_attributes(cmsino_content_params)
    redirect_to session[:cmsino_from] || root_path
  end

  def destroy
    @content = Cmsino::Content.find(params[:id])
    if @content.destroy
      flash[:notice] = "OK"
    else
      flash[:error] = "Error"
    end
    redirect_to session[:cmsino_from]
  end

  private

  def cmsino_content_params
    (params[:cmsino_content] || params[:cmsino_post]).permit(:umbrella, :date, :title, :name, :locale, :text)
  end

  def cmsino_text
    (params[:cmsino_content] || params[:cmsino_post])[:text]
  end

end

app/controllers/cmsino/media_controller.rb
class Cmsino::MediaController < ApplicationController
  layout 'cmsino/layouts/cmsino'
  authorize_resource class: Cmsino::Medium

  before_action :get_medium, only: [:edit, :update, :destroy, :toggle]

  def index
    @media = Cmsino::Medium.order(:name)
    # in case we want to add media to a content
    @content = Cmsino::Content.find(params[:content_id]) if params[:content_id]
  end

  def new
    @medium = Cmsino::Medium.new
  end

  def create
    @medium = Cmsino::Medium.new(medium_params)
    if @medium.save
      redirect_to cmsino_media_path, notice: 'file uploaded'
    else
      render action: :edit
    end
  end

  def edit
  end

  def update
    @medium.update_attributes(medium_params)
    redirect_to edit_cmsino_medium_path(@medium)
  end

  def destroy
    @media.destroy
    redirect_to cmsino_media_path
  end

  def toggle
    @content = Cmsino::Content.find(params[:content_id])
    if @content.cmsino_medium_ids.include?(@medium.id)
      @content.cmsino_media.delete(@medium)
    else
      @content.cmsino_media << @medium
    end
    render json: 'ok'
  end

  private

  def medium_params
    params[:cmsino_medium].permit(:name, :description, :attach)
  end

  def get_medium
    @medium = Cmsino::Medium.find(params[:id])
  end
end

app/controllers/cmsino/media_uses_controller.rb
class Cmsino::MediaUsesController < ApplicationController
  layout 'cmsino/layouts/cmsino'
  authorize_resource :class => Cmsino::Content

  def new
    @medium = Cmsino::Medium.find(params[:medium_id])
    @content = Cmsino::Content.find(params[:content_id])
    @content.cmsino_media << @medium
    redirect_to [:edit, @content]
  end

  def destroy
    media_use = Cmsino::MediaUse.find params[:id]
    media_use.delete
    redirect_to [:edit, media_use.cmsino_content]
  end
end

app/controllers/cmsino/pages_controller.rb
class Cmsino::PagesController < Cmsino::ContentsController
  layout 'cmsino/layouts/cmsino'
  authorize_resource class: Cmsino::Content

  before_action :available_locales

  def index
    @contents_hash = Hash.new
    Cmsino::Content.order([:umbrella, :name, :locale]).each do |content|
      @contents_hash[content.umbrella] ||= Hash.new
      @contents_hash[content.umbrella][content.name] ||= Hash.new
      @contents_hash[content.umbrella][content.name][content.locale] = content
    end
    @last_edited = session[:cmsino_last]
  end

end

app/controllers/cmsino/posts_controller.rb
class Cmsino::PostsController < Cmsino::ContentsController
  layout 'cmsino/layouts/cmsino'
  authorize_resource :class => Cmsino::Content

  def index
    @posts = Cmsino::Post.order(:umbrella, :date).includes(:cmsino_media)
  end

end

app/helpers/cmsino_helper.rb
module CmsinoHelper

  def display_editable_content(content, edit_url)
    text = (content and ! content.text.blank?) ? content.text : "edit me"

    return text.html_safe unless edit_url

    # capture do 
    #   content_tag(:div, class: 'cmsino_editable', data: { editor: edit_url }) do
    #     "&nbsp;".html_safe +
    #       content_tag(:div, class: 'cmsino-help') do
    #       'Double click to edit'
    #     end + text.html_safe
    #   end
    # end
    capture do 
      content_tag(:div, class: 'cmsino_editable', data: { editor: edit_url }, rel: 'popover') do
        text.html_safe
      end
    end
  end

  # display the current content. Eventually creates it if content with the
  # name and locale doesen't exists. 
  # Can pass page_name (example editable_content(:main, :home)
  def editable_content(name, page = nil)
    page = page ? Cmsino::Page.new(page) : @cmsino_page
    if ! page
      raise "FIXME trovare cmsino_page da snippet name quando possibile"
    end
    content = page.content(name, I18n.locale)

    edit_url = can?(:update, content) ? edit_cmsino_content_path(content) : nil
    display_editable_content(content, edit_url)

    # editable_tags = ''
    # visible_content = content.text
    # if can?(:update, content) 
    #   editable_tags = %Q|class="cmsino_editable" data-editor="#{edit_cmsino_content_path(content)}"|
    #   visible_content = 'edit me' if visible_content.blank?
    # end

    # raw %Q|
    #   <div #{editable_tags} id="#{content.div_id}">&nbsp;
    #     <div class="cmsino-help">Double click to edit</div>
    #     #{visible_content}
    #   </div>|
  end

  def selectable_image(name, style: '', cssclass: '' )
    content = Cmsino::Content.find_or_create_by(name: name, locale: I18n.locale)

    if can?(:update, content) 
      editable_tags = %Q|class="cmsino_editable" data-editor="#{cmsino_content_media_path(content)}"|
    end

    res = ''
    content.cmsino_media.each do |medium|
      res += %Q|
        <div #{editable_tags} id="#{medium.id}">&nbsp;
          <div class="cmsino-help">Double click to edit</div>
          <img src="#{medium.attach.url}" style="#{style}" class="#{cssclass}"/>
        </div>|
    end
    res.html_safe
  end

  # POSTS

  def editable_posts(name, description = nil)
    @cmsino_posts ||= Hash.new
    @cmsino_posts[name] = Cmsino::Post.where(umbrella: name).includes(:cmsino_media).order('date desc')
  end

  def icon(name, options = { text: "", size: "18" })
    raw "<i style=\"font-size: #{options[:size]}px\" class=\"fa fa-#{name}\"></i> #{options[:text]}"
  end

  # MEDIA

  # obj = content or array o media
  # pass content variable if want to give chance to add media to the content
  def ul_media(obj, content = nil)
    media = (obj.is_a? Cmsino::Content) ? obj.cmsino_media : obj # array of media
      
    content_tag :ul, class: 'row' do
      content_tag_for :li, media, class: 'thumbnail col-sm-6 col-md-4' do |media|
        delete_path = (obj.is_a? Cmsino::Content) ? (cmsino_media_use_path(obj.cmsino_media_uses.where(cmsino_medium_id: media.id).first)) : "#" 

        image_tag(media.attach.url(:medium), height: 150) +

        content_tag(:div, class: "caption") do
          content_tag(:h4,  class: "media-heading") { media.name } +
          content_tag(:p) { media.description } +
          content_tag(:p) { link_to(icon('trash'), delete_path , method: :delete) unless content } +
          content_tag(:p) { link_to(icon('plus'), new_cmsino_media_use_path(content, medium_id: media.id)) if content }
        end
      end
    end
  end

  def umbrella_div_id(umbrella)
    "umbrella_#{umbrella}"
  end

  def icon(name, options = { text: "", size: "18" })
    raw "<i style=\"font-size: #{options[:size]}px\" class=\"fa fa-#{name}\"></i> #{options[:text]}"
  end

  def cmsino_header
    render partial: 'cmsino/layouts/cmsino_header'
  end
end

app/views/cmsino/contents/edit.html.erb
<ul class="breadcrumb">
  <li><%= @content.umbrella %></li>
  <li><%= @content.name %></li>
  <li><%= @content.locale %></li>
  <li><%= @content.id %></li>
</ul>

<%= simple_form_for @content do |content| %>  
  <%= content.hidden_field :umbrella %>  
  <%= content.hidden_field :locale %>  
  <% if @content.class == Cmsino::Post %>
    <%= content.input :name %> 
    <%= content.input :date, as: :date_picker %>
  <% else %>
    <%= content.hidden_field :name %>  
  <% end %>
  <%= content.input :text %>  
  <%= content.submit %> 
<% end %>

<ul class="list-group">
  <% @all_content_locales.each do |content| %>
    <% content == @content and next %>  
    <li class="list-group-item">
      <p>
        <strong><%= content.locale %></strong>
        <%= link_to icon(:edit), edit_cmsino_content_path(content, locale: content.locale) %>
        <%= link_to icon(:trash), cmsino_content_path(content), method: :delete, data: { confirm: 'sure?' } %>
        <%= link_to icon(:copy), '#', id: 'copy-locale-content' %>
      </p>
      <div class="other_locale">
        <%= content.text %>
      </div>
    </li>
  <% end %>
</ul>

<%= ul_media(@content) %>  

<% if ! @content.new_record? %>  
  <%= link_to icon('camera') + 'add media', cmsino_content_media_path(@content), class: 'button' %>  
<% end %>

<%= javascript_tag do %>  
  $("#copy-locale-content").click(function(e) {
    e.preventDefault();
    var other_text = $(this).parent().parent().find(".other_locale").text();
    $('#cmsino_content_text').data("wysihtml5").editor.setValue(other_text);
  });
<% end %>

app/views/cmsino/contents/index.html.erb
<h1>Contents</h1>

<% id = 0 %>  
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

  <% @contents_hash.each_key do |umbrella| %>  
    <% @contents_hash[umbrella].each_key do |name| %>
      <% id = id + 1 %>  
      <% div_id = umbrella_div_id(umbrella) %>  
      <% in_class, aria_expanded = (@last_edited == div_id) ? ['in', 'true'] : ['', 'false'] %>

      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading<%= div_id %>">
          <h4 class="panel-title">
            <%# FIXME use some id or check security in page name %>
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%= id %>" aria-expanded="<%= aria_expanded %>" aria-controls="collapse<%= id %>">
              <strong><%= umbrella %></strong> > <strong><%= name ? name : umbrella %></strong>
            </a>
          </h4>
        </div><!-- panel-heading -->

        <div id="collapse<%= id %>" class="panel-collapse collapse <%= in_class %>" role="tabpanel" aria-labelledby="heading<%= id %>">
          <div class="panel-body">
            <% @all_locales.each do |locale| %>
              <% content = @contents_hash[umbrella][name][locale] %>
              <div class="row">
                <div class="col-md-1">
                  <p>
                  <strong><%= locale %></strong>
                  <% if content %>
                    <%= link_to icon(:trash), cmsino_content_path(content), method: :delete %>
                  <% else %>
                    <%= link_to icon(:plus), new_cmsino_content_path(cmsino_content: {umbrella: umbrella, name: name, locale: locale}) %>
                  <% end %>
                  </p>
                </div>
                <div class="col-md-10">
                  <% if content %>  
                    <%= display_editable_content(content, edit_cmsino_content_path(content)) %>  
                  <% end %>
                </div>
              </div>
            <% end %>
          </div><!-- panel-body -->
        </div><!-- panel-collapse -->
      </div><!-- panel -->

    <% end %><!-- page -->
  <%  end %><!-- umbrella -->

</div><!-- panel-group -->